### ISSUE TITLE
bug: parseAbi throws type error

### ISSUE THREAD

**Issue by Sam-Scolari** [wagmi-dev/abitype#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.0

### Current Behavior

The following code was [copied directly from the docs](https://viem.sh/docs/abi/parseAbi.html#usage) and throws the following type errors:

- "Type 'string' is not assignable to type 'string & [`Error: Signature "${string}" is invalid at position 0.`]'"
- "Type 'string' is not assignable to type 'string & [`Error: Signature "${string}" is invalid at position 1.`]'"

```typescript
parseAbi([`
  "function balanceOf(address owner) view returns (uint256)",
  "event Transfer(address indexed from, address indexed to, uint256 amount)",
]);
```

![Screenshot_35](https://github.com/wagmi-dev/viem/assets/56174573/b2ffa8a9-467b-4a98-81b2-fac293b6b944)

### Expected Behavior

No type error

### Steps To Reproduce

Copied directly from the docs here: https://viem.sh/docs/abi/parseAbi.html#usage

**Note**: Could not reproduce error on https://new.viem.sh with the same version, tsconfig, and code.

### Anything else?

```typescript
import { parseAbi, parseAbiItem } from "viem";

// Throws type error
parseAbi([
  "function balanceOf(address owner) view returns (uint256)",
  "event Transfer(address indexed from, address indexed to, uint256 amount)",
]);

// Doesn't throw type error
parseAbiItem("function balanceOf(address owner) view returns (uint256)");
parseAbiItem(
  "event Transfer(address indexed from, address indexed to, uint256 amount)"
);
```

```typescript
// tsconfig.json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ESNext", "DOM"],
    "moduleResolution": "Node",
    "strict": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*", "botswarm.config.ts"]
}
```

**Comment by tmm** [comment]
Looks like an issue with TypeScript 5.1.3. Looking into it! In the meantime, you can downgrade to TypeScript 5.0.4 and should work fine.

**Comment by Sam-Scolari** [comment]
Downgrading to 5.0.5 did not solve the issue.

**Package.json**
```json
{
  "name": "botswarm",
  "version": "0.0.1",
  "description": "",
  "scripts": {
    "start": "ts-node src/index.ts"
  },
  "dependencies": {
    "@types/node": "^20.3.1",
    "dotenv": "^16.1.4",
    "ts-node": "^10.9.1",
    "typescript": "^5.0.4",
    "uuid": "^9.0.0",
    "viem": "^1.0.0"
  },
  "devDependencies": {
    "@types/uuid": "^9.0.2"
  }
}
```

I have been able to bypass the error using multiple parseAbiItem's:

```typescript
abi: [
  parseAbiItem(
    "function castVote(uint256 proposalId, uint8 support) external"
  ),
  parseAbiItem(
    "event BidPlaced(address indexed dao, uint256 indexed propId, uint256 support, uint256 amount, address bidder)"
  ),
],
```

**Comment by tmm** [comment]
I would double check that TypeScript 5.0.4 is installed since the caret `^` could allow 5.1.3 to be installed.

**Comment by Sam-Scolari** [comment]
`node_modules > typescript > package.json` shows 5.0.4 is installed

![image](https://github.com/wagmi-dev/abitype/assets/56174573/4544e399-9ca3-42bf-b3d7-1350273c1132)

**Comment by Raiden1411** [comment]
For 5.1.3 as a workaround you can also try

```ts
parseAbi([
  "function balanceOf(address owner) view returns (uint256)",
  "event Transfer(address indexed from, address indexed to, uint256 amount)",
] as const);
```

or

```ts
const abi = [
  "function balanceOf(address owner) view returns (uint256)",
  "event Transfer(address indexed from, address indexed to, uint256 amount)",
] as const

parseAbi(abi);
```

**Comment by tmm** [comment]
Fixed. Will bring downstream into viem shortly.
