### ISSUE TITLE
Error when build in Nextjs 12.1.6

### ISSUE THREAD

**Issue by cungns** [wagmi-dev/abitype#160]
### Describe the bug

I'm using wallet connect 2 in  my project and when I run "npm run build" have an error 
./node_modules/viem/node_modules/abitype/dist/types/human-readable/formatAbi.d.ts:18:35
Type error: Type parameter declaration expected.

 export declare function formatAbi<const TAbi extends Abi | readonly unknown[]>(abi: TAbi): FormatAbi<TAbi>;
- How to fix errors? 

![image](https://github.com/wagmi-dev/abitype/assets/61767208/844f41b9-ec54-4c9d-8420-5c13030904cd)

### Package Version

0.8.11

### TypeScript Version

5.1.6

### Validations

- [X] Checked there isn't [already an issue](https://github.com/wagmi-dev/abitype/issues) that exists for the bug you encountered.
- [X] Followed the [Code of Conduct](https://github.com/wagmi-dev/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guide](https://github.com/wagmi-dev/abitype/blob/main/.github/CONTRIBUTING.md).

**Comment by fullpipe** [comment]
@cungns I think I found a solution. Try to update `typescript` to `^5.0.4`
```
  "typescript": "^5.0.4",
```

**Comment by cungns** [comment]
> 5.0.4

It work well for me . thank you so much @fullpipe

**Comment by lyzergic** [comment]
I'm using next 13.2.4 and have a similar issue, the error shows up if I run `tsc`, not during `next build`.

**Comment by tmm** [comment]
@lyzergic can you put together a minimal reproducible example?
