### ISSUE TITLE
TS build error: instantiation is excessively deep

### ISSUE THREAD

**Issue by jmrossy** [wagmi-dev/abitype#169]
### Describe the bug

Building with Typescript 5 fails with the following error:
```
/node_modules/abitype/dist/types/human-readable/formatAbiParameter.d.ts(19,15): error TS2589: Type instantiation is excessively deep and possibly infinite.
```

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/infallible-chatelet-98xg5y?file=%2F.codesandbox%2Fworkspace.json%3A1%2C1

### Steps To Reproduce

Build with typescript (e.g. `yarn tsc`)

### Package Version

0.8.11

### TypeScript Version

5.1.6

### Anything else?

This error arose sometime between v0.8.7 and v0.8.11. I know that because Viem 1.2.2 builds fine but Viem 1.2.3+ fails. See https://github.com/wagmi-dev/viem/pull/802/files

### Validations

- [X] Checked there isn't [already an issue](https://github.com/wagmi-dev/abitype/issues) that exists for the bug you encountered.
- [X] Followed the [Code of Conduct](https://github.com/wagmi-dev/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guide](https://github.com/wagmi-dev/abitype/blob/main/.github/CONTRIBUTING.md).

**Comment by jmrossy** [comment]
@tmm Here's a minimal codesandbox that repros the build error:
https://codesandbox.io/p/sandbox/infallible-chatelet-98xg5y?file=%2F.codesandbox%2Fworkspace.json%3A1%2C1

<img width="1187" alt="Screenshot 2023-07-14 at 10 59 41 AM" src="https://github.com/wagmi-dev/abitype/assets/710751/2dcd9dae-8f84-478a-b2e3-6af1856c2a72">

**Comment by Raiden1411** [comment]
You might want to add to your tsconfig this option `"skipLibCheck": true` to tell `tsc` to skip typechecking on `node_modules`.

**Comment by jmrossy** [comment]
> skipLibCheck

Great idea, that fixed it! Thanks, that unblocks me for me for now 🙏

**Comment by tmm** [comment]
If anyone is interested in taking this on, the `Join` type here need reworking:

https://github.com/wagmi-dev/abitype/blob/fb53bb6d4bcaae12c7b75dd62bc5a93254263956/src/human-readable/formatAbiParameter.ts#L25-L30

**Comment by Raiden1411** [comment]
I honestly think that the `Join` type is fine as it is. After some digging I found that the problem on this issue is the missing `"exactOptionalPropertyTypes": true` on the `tsconfig.json` file. I see two options here. We either try to adapt the codebase in order to work with or without the `exactOptionalPropertyTypes` flag enabled or we can add some sort of warning on the docs that if for some reason they cant use `skipLibCheck` flag in their `tsconfig` they should consider setting the `exactOptionalPropertyTypes` flag to `true`. Imo the second options seems like it would be best but I would love to hear what you think @tmm

**Comment by jmrossy** [comment]
To share one data point, my team and I would be open to enabling `exactOptionalPropertyTypes` on our monorepo but we'd prefer not to. It would break things in a few places, requiring code changes.

**Comment by tmm** [comment]
Thanks for the thoughts @Raiden1411 and @jmrossy. I'm sure we can figure out a way to get this to work without requiring any additional TypeScript configuration.

**Comment by roninjin10** [comment]
If useful info:

I copied abitype into my own repo and treated it like source code with my own tsconfig (don't ask why).  I ran into this error and setting `"exactOptionalPropertyTypes": true` was the only way I could find to make the error go away
