### ISSUE TITLE
Extra space in formatAbi return type

### ISSUE THREAD

**Issue by roninjin10** [wagmi-dev/abitype#173]
### Describe the bug

Trying to write a test that involves asserting the correct types are emited by Evmts, I noticed a mismatch between formatAbi and abitype.  Abitype has an extra space in the parameters. Not a big deal in practice but a little janky looking and for me it's blocking me asserting that Evmts LSP is emitting right type here

### Link to Minimal Reproducible Example

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgM2iAhjAggI2HAXxSghDgHJ08YBPMAU3IChRJZE4B3KYGegMWAAbegGUaAOwDGhYqQrIAzsyZSIExfHpQpAJgAMufAF44AbSYBIBFcsAiNRpjoJMOwC44MKAFd6AGls7YAkwHxhFD3MAXUDLewl0EHoou0Tkuzj7CHCwiKiLeOtbeLSklM87TJL7WgZUzR4JAHM7EoJbWKCwdBoqESjkdCFFAKDNTHoAWXCqYV4aVIA3YHpOatK6irg7ZB9pGGB1NssCOJtSxwnXQeHRrODQ8MjPQviLorKMyoB9RQYJAATbQbT5bVLoQGAqD0RSRdpZYpFBLlVI-JbDPygzZ0bZ2HwhGC6ACsADYTvEOvEuqV0nj0GAwCQlikHjkYHkXuYSh9aajKtjarjUjgIBAhBTTp0Hj0+jgBp4hiMxqUJnwZs48EIFqkJOpZf1WUFwZU9gcjhITmcrB8HOprm5PN4-A8QpyCjSUd8djAIM4hKIfIyhIs2blngUeTUvnjBXYTTsCa4SeT2tLur1DbdlQ81dNZlqdZUVmtQfHhab9lJDscrNakfYrs4boq7ir7G6I68o8iY2jkCQQHGE3ZIdDYfCivX3tG6WjfcOKzsxzC4ZLpw2+d67OjMUbeyOk0Syev01u8d4XIpkNp+IOy+z3d2iryvbHEUL6pVReLT9SZZm8rbEq9zjM46oFvMtC6vqgEDA8I5mtWFpWucQRNi4jpeL47aPE+MQPHOlTAlIoB3A+4b5M+M69kROyLl+iaEgAHH+lienYBpAdmoGquB+aalBizFqs6wIUuuxVjWlp1mhlz2s2WHOrhnZUdyL6zvyOw-BAnASCCH7loxo5Qquk6Umeb4isMLhSPQADyyAURyXbqTRnx0XYOA2dI+5ghJR4pmxHFcQqKBtrm-EanM2rQSJpbicZSHSahNroQpmFRMprpPGpZgcZ5ig0CAooSmGLl5T2HlaVUhkjo0IStGm-4ZnKYUgbhebRYWcU7CWYnGhJyUobJaXyU4mWtjmQSqVybyblZvwLnVEkrhO66Iq+fa-BiQhYitxmBSezXsYRNWXhoN5QM5+HzVtnkMXiP4SidIVwcBEVgZM3VCTBoTvWWiFSSNpxyY2GUtthLozblc1VeeaK6fp10HfSpnrQi8OLdp-z0ECBnRiOa1rq9Z3bsMQi6bZfl2I+rl3Zp26PakR2plOlmcQDU28fYXWQbFwl9aJgNDcDtag2N9ihds2VfRBgkC6k0si0lFPeVIADWqUNqOeoSMVORch1OW3VjjzAgAHvQgJZThhmeUjBMHqt6Mk1Om3RiElvW7b0O0TVuP4yjhMu+ObuUh7vZe-QVs29z7YI8We7M5UrPBWTeJYIyzLDCreL0CyNyjTrLjqAbPhG59pSzZGGlR-jse+wn2O7PeqMQq75kS3XnzR43Tp24zF4QCny6dxtZt9z78f2zVu37SHh2EkFpNBJ5AAqUBXldeepAXeNuHWTDRHA6CKHATZMKoCkoGgmB8ICRhwKYqBQBg2B4AAFNoeiGHgACUQA

### Steps To Reproduce

Use formatAbi and notice extra spaces when you hover 
![image](https://github.com/wagmi-dev/abitype/assets/35039927/909f91ca-6ca1-41c5-af68-82e50dc2aa1f)

### Package Version

0.9.3

### TypeScript Version

5.1.6

### Validations

- [X] Checked there isn't [already an issue](https://github.com/wagmi-dev/abitype/issues) that exists for the bug you encountered.
- [X] Followed the [Code of Conduct](https://github.com/wagmi-dev/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guide](https://github.com/wagmi-dev/abitype/blob/main/.github/CONTRIBUTING.md).

**Comment by tmm** [comment]
PR welcome

**Comment by roninjin10** [comment]
Won't have time to get to this til August but if still open I can definitely take this one on likely an easy fix

**Comment by roninjin10** [comment]
Holy closed before vacation started so I can use this right away! Ya'll are the goats!
