### ISSUE TITLE
Compilation issue with TypeScript 5.2.2

### ISSUE THREAD

**Issue by frangio** [wagmi-dev/abitype#204]
### Describe the bug

I'm seeing the following compiler error when using TypeScript 5.2.2:

```
$ npx tsc
src/utils.ts:3:35 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("abitype")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

3 import type { AbiParameter } from 'abitype';
                                    ~~~~~~~~~
```

I have these settings in my tsconfig.json:
```
"module": "node16",
"moduleResolution": "node16",
```

I noticed that abitype publishes CommonJS files with a `.js` extension, even though in package.json it says `"type": "module"`. Manually changing `"type": "module"` to `"type": "commonjs"` fixes the compiler error. This seems like an odd fix because ES modules are also published with a `.js` extension, however those are perhaps hardcoded to be interpreted as ES modules because they are reached through the explicit `"import"` entrypoints?

### Link to Minimal Reproducible Example

The playground doesn't work with ES Modules.

### Package Version

0.10.1

I don't see the same issue with 0.9.10.

### TypeScript Version

5.2.2

### Validations

- [X] Checked there isn't [already an issue](https://github.com/wagmi-dev/abitype/issues) that exists for the bug you encountered.
- [X] Followed the [Code of Conduct](https://github.com/wagmi-dev/.github/blob/main/CODE_OF_CONDUCT.md).

**Comment by Raiden1411** [comment]
Could you share a reproducible link to your tsconfig and package.json?

**Comment by frangio** [comment]
https://github.com/frangio/repro-abitype-error

See error with `npx tsc`

**Comment by Raiden1411** [comment]
We had this same problem when we migrated to use TS 5.2.2. This was because of a change in typescripts module/moduleResolution that you can check [here](https://github.com/microsoft/TypeScript/issues/55705).

To have it run as cjs your `tsconfig.json` must now be like this:

```json
"module": "CommonJS",
"moduleResolution": "Node10"
```

Some more details of the changes in typescript can be found on this [PR](https://github.com/microsoft/TypeScript/pull/54567) and this [issue](https://github.com/microsoft/TypeScript/issues/54593).

Hope this help!

**Comment by frangio** [comment]
Changing `abitype` so that it says `"type": "commonjs"` in package.json fixes this. Do you see a reason why abitype shouldn't make this change?

**Comment by tmm** [comment]
What we need to do is to emit `package.json` files to each `dist` directory (e.g. `dist/esm` and `dist/cjs`) with the specific module type defined there. Can [see how this works in Viem](https://github.com/wagmi-dev/viem/blob/main/package.json#L9-L10).

**Comment by frangio** [comment]
Oh, that actually seems to be the case already: 

https://github.com/wagmi-dev/abitype/blob/32cf12dcece9f7ef0d3e06376b81feb52dc801be/packages/abitype/package.json#L9

This made me realize that the error only happens if my project has `"type": "commonjs"` (explicitly or implicitly as the default). It also happens with normal `import` (as opposed to `import type`), but in this case the error is obviously a TypeScript bug where it doesn't seem to consider the `exports` field in package.json? In the case of `import type` it actually also sounds like a TypeScript bug to me. I will look into it more and report it upstream...

Closing this issu. FWIW, I don't think there is any possible workaround that abitype could implement.

**Comment by frangio** [comment]
After some more experimentation I've found that the error is caused by having `"type": "module"` in a place that affects abitype's `.d.ts` files. Now I understand that this is what @tmm was suggesting.
