### ISSUE TITLE
Conflict with Typescript version

### ISSUE THREAD

**Issue by DJayFreshBlock** [wagmi-dev/abitype#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.8-0.2.5

### TypeScript Version

4.6.4

### Current Behavior

Multiple errors in index.d.ts trying to compile.

`node_modules/abitype/dist/index.d.ts:77:66 - error TS1005: '?' expected. components: infer TComponents extends readonly AbiParameter[];`

### Expected Behavior

Type definitions shouldn't cause errors even in a version behind the project. Considering @wagmi/core TS is 4.6.4 also.

### Steps To Reproduce

Inside Package.json

```
"dependencies": {
    "abitype": "^0.1.8",
    "typescript": "^4.6.4"
  }
```

test.ts
```
import { Address } from 'abitype';

export const address: Address = '0x';
```

run: `tsc test.ts`

### Anything else?

I'm running into this issue while working inside of an Angular project which can't upgrade to TS 4.7+ at this time. I'm unable to use  the below package due to the shared dependency of abitype:

- @web3modal/ethereum

**Comment by tmm** [comment]
ABIType supports [versions 4.7.4 and above](https://github.com/wagmi-dev/abitype/blob/main/package.json#L38) so 4.6.4 will not work unfortunately.
